### ISSUE TITLE
[Root-Task] 전체 진행

### ISSUE THREAD

**Issue by juo1221** [juo1221/catPhotos-mvvm#2]
### Todo

- [x]  첫 api load 후 클릭 시 directory 이동
- [x] 뒤로가기 기능 구현
- [x] 데이터 캐싱 기능 구현
- [x] breadCrumb 경로 보이기
- [x] breadCrumb 클릭 시 경로 이동 기능 구현
- [x] 이미지 파일 클릭 시 이미지 모달 띄우기
- [x] 로딩 스피너 기능 구현
- [x] 파일 분리
